version: '3'

services:
  db:
    image: mysql
    container_name: db
    ports:
      - "3306"
    env_file: .env
    environment:
      MYSQL_DATABASE: "moviedb"
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "root"
    
  django:
    build: ./back-end
    container_name: backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    # volumes: 
    #   - .:./back-end

  frontend:
    build: ./front-end
    container_name: frontend
    command: ["yarn", "start"]
    ports:
      - "3000:3000"